=== KnetMiner/genomaps.js/src/test/data/basemapSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "index": {
        "type": "number"
      },
      "length": {
        "type": "number"
      },
      "number": {
        "type": "number"
      },
      "bands": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "index": {
              "type": "number"
            },
            "start": {
              "type": "number"
            },
            "end": {
              "type": "number"
            },
            "color": {
              "type": "string"
            }
          }
        }
      }
    },
    "required": [
      "index",
      "length",
      "number",
      "bands"
    ]
  }
}

=== KnetMiner/genomaps.js/src/test/data/basemap/schemaExample.json
[
    {
        "index": 1,
        "length": 30427671,
        "number": 1,
        "bands": [{
        "index": 1,
        "start": 0,
        "end": 30427671,
        "color": "0xFFFFFF"
        }]
    },
    {
        "index": 2,
        "length": 19698289,
        "number": 2,
        "bands": [{
        "index": 1,
        "start": 0,
        "end": 19698289,
        "color": "0xFFFFFF"
        }]
    },
    {
        "index": 3,
        "length": 23459830,
        "number": 3,
        "bands": []
    }
]
